### ISSUE TITLE
Organize content-mapping-edit-a-thon

### ISSUE THREAD

**Issue by machikoyasuda** [trailangeles/trailangeles#58]
## Tasks

- [ ] Add trailhead locations as pins (Lat / Lon) attached to a Trail as a Place
- [ ] Start with trailheads of recent volunteer event locations
- [ ] For Max: Update OSM with propert trail condition data
- [ ] Add organizations from the GitHub issue to the back-end and find locations (like Visitor's Centers, fire lookouts, points of interest like observatories)
- [ ] Then add trailheads with the most prominent car parking spots along the 2, 39 and the Santa Clarita areas
